# week 02 - part 02 - assignment 01

In [1]:
import numpy as np
import pandas as pd
import sys

# Загрузите выборку из файла svm-data.csv

In [ ]:
main_data = pd.read_csv('svm-data_with_headers.csv')
X_data = main_data[['B','C']]
Y_data = main_data['A']
type(Y_data)
print X_data
print Y_data

      B     C
0  0.70  0.29
1  0.23  0.55
2  0.72  0.42
3  0.98  0.68
4  0.48  0.39
5  0.34  0.73
6  0.44  0.06
7  0.40  0.74
8  0.18  0.18
9  0.53  0.53
0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    1
8    0
9    1
Name: A, dtype: float64


# Обучите классификатор с линейным ядром, параметром C = 100000 и random_state=241. 
 
 kernel='linear'
 C = 100000 
 random_state=241. 
 
 

In [18]:
from sklearn.svm import SVC
# Create classifiier
clf = SVC(C=100000,random_state=241,kernel='linear')




In [19]:
# Fit the SVM model according to the given training data.
# Обучите классификатор 
clf.fit(X_data, Y_data) 

SVC(C=100000, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=241, shrinking=True,
  tol=0.001, verbose=False)

In [20]:
# Индексы опорных объектов обученного классификатора хранятся в поле support_
print clf.support_
#[3 4 9]  руками добавил 1 - чтобы как по условию начинать с 1 а не с 0

[3 4 9]


In [17]:
print clf.support_vectors_

[[ 0.72  0.42]
 [ 0.98  0.68]
 [ 0.48  0.39]
 [ 0.18  0.18]
 [ 0.23  0.55]
 [ 0.34  0.73]
 [ 0.4   0.74]
 [ 0.53  0.53]]
